"use client"
import Link from "next/link"
import { useEffect, useState } from "react"
type Loan = { id:string; loanAmount:string; outstanding:string; status:string; verificationStatus:string; member:{name:string}; loanProduct?:{name:string}|null }
export default function LoansPage() {
 const [loans,setLoans]=useState<Loan[]>([]); const [error,setError]=useState("")
 useEffect(()=>{fetch("/api/loans").then(async r=>r.ok?setLoans(await r.json()):setError((await r.json()).error||"Could not load loans")).catch(()=>setError("Could not load loans"))},[])
 const pending=loans.filter(l=>["PENDING","DRAFT","SUBMITTED","UNDER_REVIEW"].includes(l.status)||l.verificationStatus==="PENDING")
 return <div className="flex flex-col gap-8 lg:gap-12"><div className="flex justify-between items-end gap-6"><div><h1 className="text-[44px] font-serif">Loan Portfolio</h1><p className="text-slate-500">Live portfolio, applications, and outstanding balances.</p></div><Link href="/app/loans/new" className="rounded-full bg-navy-900 px-5 py-3 text-white">New Application</Link></div>{error&&<p className="rounded bg-red-50 p-4 text-red-700">{error}</p>}{pending.length>0&&<section className="rounded-3xl bg-brand-50 p-8"><h2 className="text-xl font-medium">Review queue ({pending.length})</h2>{pending.map(l=><Link key={l.id} href={`/app/loans/${l.id}`} className="mt-4 flex justify-between border-b py-3"><span>{l.member.name} · {l.loanProduct?.name||"Product unavailable"}</span><span>LKR {Number(l.loanAmount).toLocaleString()}</span></Link>)}</section>}<section className="overflow-x-auto rounded-3xl bg-slate-50 p-8"><h2 className="mb-6 text-xl font-medium">All loans</h2><table className="w-full text-left"><thead><tr className="border-b"><th>Borrower</th><th>Product</th><th>Amount</th><th>Outstanding</th><th>Status</th></tr></thead><tbody>{loans.map(l=><tr key={l.id} className="border-b"><td className="py-4"><Link className="underline" href={`/app/loans/${l.id}`}>{l.member.name}</Link></td><td>{l.loanProduct?.name||"—"}</td><td>LKR {Number(l.loanAmount).toLocaleString()}</td><td>LKR {Number(l.outstanding).toLocaleString()}</td><td>{l.status}</td></tr>)}</tbody></table>{!loans.length&&!error&&<p className="py-8 text-slate-500">Loading loans…</p>}</section></div>
}
