-- Milestone 1 is additive. Existing Member.groupNumber and historical repayments remain intact.
CREATE TYPE "GroupStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'CLOSED');
CREATE TYPE "GroupMembershipStatus" AS ENUM ('ACTIVE', 'LEFT');
CREATE TYPE "GroupMembershipRole" AS ENUM ('MEMBER', 'LEADER', 'ASSISTANT_LEADER');
CREATE TYPE "LoanCalculationMethod" AS ENUM ('FLAT', 'DECLINING_BALANCE', 'FIXED_INSTALLMENT');
CREATE TYPE "InterestMethod" AS ENUM ('NONE', 'FLAT', 'DECLINING_BALANCE');
CREATE TYPE "RepaymentFrequency" AS ENUM ('DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'CUSTOM');
CREATE TYPE "PaymentAllocationComponent" AS ENUM ('PRINCIPAL', 'INTEREST', 'PENALTY', 'FEE');
CREATE TYPE "RepaymentTransactionType" AS ENUM ('PAYMENT', 'REVERSAL');
CREATE TYPE "PaymentReversalStatus" AS ENUM ('REQUESTED', 'APPROVED', 'REJECTED');
ALTER TYPE "LoanStatus" ADD VALUE IF NOT EXISTS 'DRAFT'; ALTER TYPE "LoanStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED'; ALTER TYPE "LoanStatus" ADD VALUE IF NOT EXISTS 'UNDER_REVIEW'; ALTER TYPE "LoanStatus" ADD VALUE IF NOT EXISTS 'VERIFIED'; ALTER TYPE "LoanStatus" ADD VALUE IF NOT EXISTS 'APPROVED'; ALTER TYPE "LoanStatus" ADD VALUE IF NOT EXISTS 'DISBURSED'; ALTER TYPE "LoanStatus" ADD VALUE IF NOT EXISTS 'OVERDUE';
ALTER TABLE "LoanProduct" ADD COLUMN "calculationMethod" "LoanCalculationMethod" NOT NULL DEFAULT 'FLAT', ADD COLUMN "interestMethod" "InterestMethod" NOT NULL DEFAULT 'FLAT', ADD COLUMN "repaymentFrequency" "RepaymentFrequency" NOT NULL DEFAULT 'WEEKLY', ADD COLUMN "term" INTEGER, ADD COLUMN "gracePeriod" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "minimumAmount" DECIMAL(12,2), ADD COLUMN "maximumAmount" DECIMAL(12,2), ADD COLUMN "minimumTerm" INTEGER, ADD COLUMN "maximumTerm" INTEGER;
CREATE TABLE "Group" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "branchId" TEXT NOT NULL, "centreId" TEXT NOT NULL, "groupNumber" INTEGER NOT NULL, "name" TEXT NOT NULL, "leaderMemberId" TEXT, "formationDate" DATE, "meetingDay" TEXT, "meetingTime" TEXT, "status" "GroupStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Group_pkey" PRIMARY KEY ("id"));
CREATE TABLE "GroupMembership" ("id" TEXT NOT NULL, "groupId" TEXT NOT NULL, "memberId" TEXT NOT NULL, "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "leftAt" TIMESTAMP(3), "status" "GroupMembershipStatus" NOT NULL DEFAULT 'ACTIVE', "role" "GroupMembershipRole" NOT NULL DEFAULT 'MEMBER', CONSTRAINT "GroupMembership_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Group_organizationId_centreId_groupNumber_key" ON "Group"("organizationId", "centreId", "groupNumber"); CREATE INDEX "Group_organizationId_branchId_idx" ON "Group"("organizationId", "branchId"); CREATE INDEX "Group_centreId_status_idx" ON "Group"("centreId", "status"); CREATE INDEX "GroupMembership_memberId_status_idx" ON "GroupMembership"("memberId", "status"); CREATE INDEX "GroupMembership_groupId_status_idx" ON "GroupMembership"("groupId", "status");
ALTER TABLE "Group" ADD CONSTRAINT "Group_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Group" ADD CONSTRAINT "Group_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Group" ADD CONSTRAINT "Group_centreId_fkey" FOREIGN KEY ("centreId") REFERENCES "Centre"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "GroupMembership" ADD CONSTRAINT "GroupMembership_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "Group"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "GroupMembership" ADD CONSTRAINT "GroupMembership_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "LoanRepayment" ADD COLUMN "transactionType" "RepaymentTransactionType" NOT NULL DEFAULT 'PAYMENT', ADD COLUMN "reversalOfId" TEXT, ADD COLUMN "allocationMethod" TEXT; CREATE UNIQUE INDEX "LoanRepayment_reversalOfId_key" ON "LoanRepayment"("reversalOfId"); ALTER TABLE "LoanRepayment" ADD CONSTRAINT "LoanRepayment_reversalOfId_fkey" FOREIGN KEY ("reversalOfId") REFERENCES "LoanRepayment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "PaymentAllocation" ("id" TEXT NOT NULL, "paymentId" TEXT NOT NULL, "component" "PaymentAllocationComponent" NOT NULL, "amount" DECIMAL(12,2) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PaymentAllocation_pkey" PRIMARY KEY ("id")); CREATE INDEX "PaymentAllocation_paymentId_idx" ON "PaymentAllocation"("paymentId"); ALTER TABLE "PaymentAllocation" ADD CONSTRAINT "PaymentAllocation_paymentId_fkey" FOREIGN KEY ("paymentId") REFERENCES "LoanRepayment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "PaymentReversal" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "repaymentId" TEXT NOT NULL, "reversalPaymentId" TEXT, "status" "PaymentReversalStatus" NOT NULL DEFAULT 'REQUESTED', "reason" TEXT NOT NULL, "requestedById" TEXT NOT NULL, "approvedById" TEXT, "requestedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "approvedAt" TIMESTAMP(3), CONSTRAINT "PaymentReversal_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "PaymentReversal_repaymentId_key" ON "PaymentReversal"("repaymentId"); CREATE UNIQUE INDEX "PaymentReversal_reversalPaymentId_key" ON "PaymentReversal"("reversalPaymentId"); CREATE INDEX "PaymentReversal_organizationId_status_idx" ON "PaymentReversal"("organizationId", "status"); ALTER TABLE "PaymentReversal" ADD CONSTRAINT "PaymentReversal_repaymentId_fkey" FOREIGN KEY ("repaymentId") REFERENCES "LoanRepayment"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "PaymentReversal" ADD CONSTRAINT "PaymentReversal_reversalPaymentId_fkey" FOREIGN KEY ("reversalPaymentId") REFERENCES "LoanRepayment"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "PaymentReversal" ADD CONSTRAINT "PaymentReversal_requestedById_fkey" FOREIGN KEY ("requestedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "PaymentReversal" ADD CONSTRAINT "PaymentReversal_approvedById_fkey" FOREIGN KEY ("approvedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
